# 기본 설정
spring:
  profiles:
    default: local # (프로파일 기본값 로컬로 지정)

  application:
    name: fridaymarket_resource

  # .env import
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        ddl-auto: none
        id:
          new_generator_mappings: true
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  sql:
    init:
      mode: never # 서버 실행 시 data.sql 파일 항상 실행

# 서버 포트 설정
server:
  port: ${SERVER_PORT}

---

spring:
  config:
    activate:
      on-profile: local

# gRPC 서버 포트 설정
grpc:
  server:
    port: ${GRPC_RESOURCE_SERVER_PORT}
  client:
    auth:
      address: ${GRPC_HOST}:${GRPC_AUTH_SERVER_PORT}
      negotiation-type: plaintext
